"preserve_hierarchy": true

files:
  - source: /app/src/main/res/values/strings.xml
    "translation": "/app/src/main/res/values-%two_letters_code%/%original_file_name%",
    "type": "android",
#     "dest": "/app/strings.xml",
    "skip_untranslated_strings": true
