name: Build Test

on:
  push:
    branches:
      - "master"
      - "dev"
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
      - "crowdin.yml"
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.19.1

      - name: Build tts-server-lib
        run: |
          cd tts-server-lib
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
          go get golang.org/x/mobile/bind
          gomobile bind -ldflags "-s -w" -v -androidapi=19
          cp -f *.aar $GITHUB_WORKSPACE/app/libs

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: tts-server-lib
          path: tts-server-lib/*.aar

  build:
    needs: prepare
    strategy:
      matrix:
        product: [ app, dev ]
        
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      product: ${{ matrix.product }}
      type: ${{ matrix.type }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
            name: tts-server-lib
            path: ${{ github.workspace }}/app/libs

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Init Signature
        run: |
          touch local.properties
          echo ALIAS_NAME='${{ secrets.ALIAS_NAME }}' >> local.properties
          echo ALIAS_PASSWORD='${{ secrets.ALIAS_PASSWORD }}' >> local.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> local.properties
          echo KEY_PATH='./key.jks' >> local.properties
          # 从Secrets读取无换行符Base64解码, 然后保存到到app/key.jks
          echo ${{ secrets.KEY_STORE }} | base64 --decode > $GITHUB_WORKSPACE/app/key.jks

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemble${{ env.product }}release --build-cache --parallel --daemon --warning-mode all

      - name: Get VerName
        run: |
          echo "ver_name=$(grep -m 1 'versionName' ${{ github.workspace }}/app/build/output/apk/${{ env.product }}/release/output-metadata.json | cut -d\" -f4)" >> $GITHUB_ENV
        
      - name: Upload Mappings to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mappings_${{ env.product }}_${{ env.ver_name }}
          path: ${{ github.workspace }}/app/build/outputs/mapping/*.txt

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "TTS-Server_${{ env.product }}_${{ env.ver_name }}"
          path: ${{ github.workspace }}/app/build/outputs/apk/${{ env.product }}/release/*${{ env.ver_name }}.apk
